# Generated by Django 6.0 on 2026-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
    ]
