# Generated by Django 6.0 on 2026-05-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_alter_resume_extracted_text_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resume'),
        ),
    ]
